steps:
  # gcloudビルダーを使用してSecret ManagerからFirebase設定を取得
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Secret ManagerからFirebase設定を取得
        gcloud secrets versions access latest --secret="firebase-api-key" > /workspace/firebase-api-key
        gcloud secrets versions access latest --secret="firebase-auth-domain" > /workspace/firebase-auth-domain
        gcloud secrets versions access latest --secret="firebase-project-id" > /workspace/firebase-project-id
        gcloud secrets versions access latest --secret="firebase-storage-bucket" > /workspace/firebase-storage-bucket
        gcloud secrets versions access latest --secret="firebase-messaging-sender-id" > /workspace/firebase-messaging-sender-id
        gcloud secrets versions access latest --secret="firebase-app-id" > /workspace/firebase-app-id
        gcloud secrets versions access latest --secret="firebase-measurement-id" > /workspace/firebase-measurement-id || echo "" > /workspace/firebase-measurement-id

  # Secret Managerのシークレットを使用してDockerイメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # ファイルからFirebase設定を読み取り
        FIREBASE_API_KEY=$$(cat /workspace/firebase-api-key)
        FIREBASE_AUTH_DOMAIN=$$(cat /workspace/firebase-auth-domain)
        FIREBASE_PROJECT_ID=$$(cat /workspace/firebase-project-id)
        FIREBASE_STORAGE_BUCKET=$$(cat /workspace/firebase-storage-bucket)
        FIREBASE_MESSAGING_SENDER_ID=$$(cat /workspace/firebase-messaging-sender-id)
        FIREBASE_APP_ID=$$(cat /workspace/firebase-app-id)
        FIREBASE_MEASUREMENT_ID=$$(cat /workspace/firebase-measurement-id)
        
        # ビルド引数を使用してDockerイメージをビルド
        docker build \
          --build-arg NEXT_PUBLIC_FIREBASE_API_KEY="$${FIREBASE_API_KEY}" \
          --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="$${FIREBASE_AUTH_DOMAIN}" \
          --build-arg NEXT_PUBLIC_FIREBASE_PROJECT_ID="$${FIREBASE_PROJECT_ID}" \
          --build-arg NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="$${FIREBASE_STORAGE_BUCKET}" \
          --build-arg NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="$${FIREBASE_MESSAGING_SENDER_ID}" \
          --build-arg NEXT_PUBLIC_FIREBASE_APP_ID="$${FIREBASE_APP_ID}" \
          --build-arg NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID="$${FIREBASE_MEASUREMENT_ID}" \
          -t gcr.io/$PROJECT_ID/next-app \
          ./app

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/next-app']

  # Cloud Runにデプロイ
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'run'
      - 'deploy'
      - 'interrogation-app'
      - '--image=gcr.io/$PROJECT_ID/next-app'
      - '--region=asia-northeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--service-account=interrogation-app@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
      - '--set-env-vars=GOOGLE_CLOUD_LOCATION=asia-northeast1'
      - '--set-env-vars=NODE_ENV=production'
      - '--memory=2Gi'
      - '--cpu=1'
      - '--timeout=300'
      - '--concurrency=1000'
      - '--max-instances=10'

images:
  - 'gcr.io/$PROJECT_ID/next-app'