openapi: 3.0.0
info:
  title: Interrogation Room API
  version: 1.0.0
  description: ユーザーの尋問ゲーム用API仕様

servers:
  - url: https://your-app-url.com

paths:
  /api/cases:
    post:
      summary: 新しい尋問ケースを作成
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                scenarioId:
                  type: string
      responses:
        '200':
          description: 作成されたcase情報を返す
          content:
            application/json:
              schema:
                type: object
                properties:
                  caseId:
                    type: string
                  status:
                    type: string

    get:
      summary: ユーザーのすべてのケースを取得
      responses:
        '200':
          description: ケース一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Case'

  /api/cases/{caseId}:
    get:
      summary: 特定の尋問ケースを取得
      parameters:
        - name: caseId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ケース詳細
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Case'

  /api/cases/{caseId}/chat:
    post:
      summary: 尋問メッセージを送信
      parameters:
        - name: caseId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        '200':
          description: 容疑者の応答
          content:
            application/json:
              schema:
                type: object
                properties:
                  reply:
                    type: string
                  suspectState:
                    type: string
                  confessionScore:
                    type: integer
                  status:
                    type: string

  /api/auth/login:
    post:
      summary: FirebaseのIDトークンでログイン処理
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                idToken:
                  type: string
      responses:
        '200':
          description: ログイン成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  uid:
                    type: string

  /api/auth/me:
    get:
      summary: 現在ログイン中のユーザー情報を取得
      responses:
        '200':
          description: ユーザープロフィール
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    Case:
      type: object
      properties:
        caseId:
          type: string
        scenarioId:
          type: string
        status:
          type: string
        turnCount:
          type: integer
        confessionScore:
          type: integer
        suspectState:
          type: string

    User:
      type: object
      properties:
        userId:
          type: string
        displayName:
          type: string
        email:
          type: string